# -*- coding: utf-8 -*-
"""Código Actividad 2 - Búsqueda y sistemas basados en reglas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ln9-YQZt3uvayA_WNs1IMZr_VwU2yv45
"""

#!pip install experta --no-deps
#!pip install frozendict==2.3.4
# Limpiar instalaciones previas
!pip uninstall -y experta frozendict schema

# Instalar correctamente
!pip install experta --no-deps
!pip install frozendict==2.3.4 schema

import networkx as nx

def grafo():

  G = nx.Graph()

  G.add_node("Punto A")
  G.add_node("Punto B")
  G.add_node("Punto C")
  G.add_node("Punto D")
  G.add_node("Punto E")
  G.add_node("Punto F")
  G.add_node("Punto G")
  G.add_node("Punto H")
  G.add_node("Punto I")
  G.add_node("Punto J")
  G.add_node("Punto K")


  G.add_edge("Punto A", "Punto B", weight=2)
  G.add_edge("Punto B", "Punto C", weight=3)
  G.add_edge("Punto B", "Punto D", weight=3)
  G.add_edge("Punto C", "Punto D", weight=6)
  G.add_edge("Punto C", "Punto E", weight=15)
  G.add_edge("Punto D", "Punto E", weight=4)
  G.add_edge("Punto D", "Punto G", weight=5)
  G.add_edge("Punto E", "Punto F", weight=5)
  G.add_edge("Punto E", "Punto I", weight=1)
  G.add_edge("Punto F", "Punto I", weight=7)
  G.add_edge("Punto F", "Punto G", weight=2)
  G.add_edge("Punto G", "Punto H", weight=4)
  G.add_edge("Punto I", "Punto J", weight=2)
  G.add_edge("Punto J", "Punto K", weight=4)

  return G

from experta import KnowledgeEngine, Rule, MATCH, Fact

class Punto(Fact):
  """Informacion sobre un punto del transporte."""
  pass

class Ruta(Fact):
  """Informacion sobre una ruta de transporte."""
  pass

class SistemaTransporteMasivo(KnowledgeEngine):

  def __init__(self, grafo):
      super().__init__()
      self.grafo = grafo

  @Rule(Punto(nombre=MATCH.nombre, estado='lleno'))

  def evitar_punto_lleno_de_transporte(self, nombre):

    if self.grafo.has_node(nombre):
        conexiones = list(self.grafo.edges(nombre))
        self.grafo.remove_edges_from(conexiones)
        print(f"Punto de transporte '{nombre}' ha sido deshabilitado, Rutas eliminadas.")

  @Rule(Ruta(origen=MATCH.origen, destino=MATCH.destino, estado='no disponible'))
  def evitar_ruta_no_disponible_de_transporte(self, origen, destino):
    if self.grafo.has_edge(origen, destino):
        self.grafo.remove_edge(origen, destino)
        print(f"Ruta de transporte: {origen} -> {destino} no disponible, Ruta eliminada.")

def aplicar_reglas(engine):
    engine.reset()
    engine.declare(Punto(nombre='Punto F', estado='lleno'))
    engine.declare(Ruta(origen='Punto I', destino='Punto J', estado='no disponible'))
    engine.run()

