# -*- coding: utf-8 -*-
"""Código Actividad 2 - Búsqueda y sistemas basados en reglas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ln9-YQZt3uvayA_WNs1IMZr_VwU2yv45
"""

import networkx as nx
import matplotlib.pyplot as plt


def main():
    G = grafo()

    #-----------------Graficos-------------------

    #-----------------Grafico Original-------------------
    pos = nx.spring_layout(G, k=1.5, seed=40)
    fig, axs = plt.subplots(1, 2, figsize=(12, 6))

    axs[0].set_title("Grafo original")
    nx.draw(G, pos, with_labels=True, node_size=300, node_color="lightblue",font_size=8,width=2,edge_color="gray", ax=axs[0])
    labels = nx.get_edge_attributes(G, "weight")
    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels, font_size=7,ax=axs[0])

    engine = SistemaTransporteMasivo(G)
    aplicar_reglas(engine)


    #-----------------Grafico Con reglas-------------------
    axs[1].set_title("Grafo después de aplicar reglas")
    nx.draw(G, pos, with_labels=True, node_size=300, node_color="lightblue",font_size=8,width=2,edge_color="gray", ax=axs[1])
    labels = nx.get_edge_attributes(G, "weight")
    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels, font_size=7, ax=axs[1])

    plt.ion()
    plt.show(block=False)

if __name__ == "__main__":
    main()

import networkx as nx


def main():
    G = grafo()

    engine = SistemaTransporteMasivo(G)
    aplicar_reglas(engine)

  #-----Solicitud de datos para ruta en transporte---------

    origen = input("Ingrese el punto de origen: ")
    destino = input("Ingrese el punto de destino: ")

    try:
        ruta_corta = nx.dijkstra_path(G, source=origen, target=destino, weight="weight")
        tiempo_total = nx.dijkstra_path_length(
            G, source=origen, target=destino, weight="weight"
        )

        #Imprimimos el resultado y el tiempo que tomaria de acuerdo al peso
        print(f"La mejor ruta desde {origen} hasta {destino} es: {ruta_corta}")
        print(f"Tiempo total estimado: {tiempo_total} minutos")
    except nx.NetworkXNoPath:
        print(f"No hay ruta disponible desde {origen} hasta {destino}")

if __name__ == "__main__":
    main()